### PR TITLE
feat: random background images

### PR DESCRIPTION
**Pull request by chturner94**
I added functionality that instructs wezterm to randomly select a background when launching the terminal, rather than having to make changes to the config manually to change background.

Hello Kevin, I absolutely love this wezterm configuration, and I've forked it for myself as a bases for my own configuration. I also loved the wallpapers that you had sourced in your config, but I wanted them to be selected at random whenever I launched wezterm. I added the functionality to my configuration, and I mainly wanted to pass it over to you in case it was something you also liked the idea. Feel free to add it to the main repo if you would like. If not, that is totally fine. I figured it was small contribution to an amazing configuration that you put together. 

Thank you,

### CODE REVIEW

**Review by KevinSilvester — APPROVED** [review]

**Review by KevinSilvester — APPROVED** [review]
This is neat 😎

**Review by KevinSilvester — APPROVED** [review]
I'd personally prefer to keep the default shell as fish.
I'll merge it in and change it back.

**Comment by KevinSilvester** [comment]
Hi @chturner94 thanks for the contribution 😊

**Comment by chturner94** [comment]
> I'd personally prefer to keep the default shell as fish. I'll merge it in and change it back.

Thanks for kindly fixing that. My git was not very clean when I originally did this, so I likely didn't do a good job just committing the feature add. Thanks for taking my pull request! Glad you liked it!

**Pull request merged**
